/**
 * All on-screen Uzbek (Latin) copy. Conventions (enforced by tests):
 * - o‘ / g‘ use U+2018 (‘); tutuq belgisi uses U+2019 (’).
 * - No digits here: numbers come from facts.ts / caseStudies.ts.
 * - Large statements ≤ 12 words.
 */
export const NARRATIVE = {
  gate: {
    kicker: 'Interaktiv hujjatli taqdimot',
    title: 'O‘RMON',
    subtitle: 'yo‘qolayotgan nafas',
    question: 'Agar o‘rmonlar yo‘qolsa?',
    enter: 'O‘rmonga kirish',
    resume: 'Davom ettirish',
    withSound: 'ovoz bilan',
    enterQuiet: 'Ovozsiz kirish',
    restart: 'Boshidan boshlash',
    hint: 'Sichqoncha g‘ildiragi, sensorli panel yoki ↓ tugmasi bilan oldinga yuring. Ovozni istalgan payt M tugmasi bilan yoqish yoki o‘chirish mumkin.',
  },

  intro: {
    once: 'Bir paytlar bu yerda o‘rmon bor edi.',
    notOnly: 'O‘rmon faqat daraxtlardan iborat emas.',
    alive: 'U nafas oladi, suvni ushlab turadi, son-sanoqsiz hayotga boshpana beradi.',
    notJust: 'Bu faqat daraxtning yo‘qolishi emas.',
    system: 'Bu butun tizimning o‘zgarishi.',
    srTree: 'Markazdagi baland daraxt qulaydi; o‘rmon rangi xiralashadi, yorug‘lik qattiqlashadi.',
  },

  system: {
    title: 'Har bir qism boshqasiga bog‘liq.',
    instruction: 'Belgini tanlang — bog‘lanishlar yorishadi.',
    all: 'Butun tizim',
    equationLeft: 'o‘rmon =',
    equationBefore: 'daraxtlar',
    equationAfter: 'bog‘langan tirik tizim',
    tags: {
      co2: 'CO2',
      o2: 'O2',
      carbon: 'uglerod: tana, ildiz, tuproq',
      threads: 'zamburug‘ iplari (mikoriza)',
      litter: 'to‘shama suvni shimadi',
      grip: 'ildizlar tuproqni ushlaydi',
      evaporation: 'bug‘lanish',
      rain: 'yomg‘ir',
      groundwater: 'yer osti suvi',
      stream: 'irmoq',
      deer: 'kiyik',
      bird: 'qush',
      fox: 'tulki',
      hare: 'quyon',
      owl: 'boyo‘g‘li',
      insects: 'hasharotlar',
      fungi: 'zamburug‘lar',
      shade: 'salqin va nam',
      open: 'ochiq joy: issiqroq',
    },
    hotspots: {
      tree: {
        label: 'Daraxt',
        title: 'Uglerod ombori',
        text: 'Barglar havodan karbonat angidridni yutadi. Uglerod tanada, ildizda va tuproqda uzoq yillar saqlanadi.',
      },
      roots: {
        label: 'Ildizlar',
        title: 'Yashirin hamkorlik',
        text: 'Ildizlar zamburug‘ iplari bilan hamkorlikda (mikoriza) suv va oziq moddalarni oladi. Bu tarmoq ko‘rinmaydi, lekin o‘rmonni ushlab turadi.',
      },
      soil: {
        label: 'Tuproq',
        title: 'Tirik gubka',
        text: 'O‘rmon to‘shamasi yomg‘irni shimadi, ildizlar tuproqni mahkam ushlaydi. Shuning uchun o‘rmonda tuproq kam yuviladi.',
      },
      water: {
        label: 'Suv',
        title: 'Yopiq aylanma',
        text: 'Daraxtlar tuproqdagi suvni barglar orqali bug‘latadi. Bu namlik bulutlarga qo‘shilib, yana yomg‘ir bo‘lib qaytadi.',
      },
      wildlife: {
        label: 'Hayvonot',
        title: 'Oziq to‘ri',
        text: 'Har bir tur boshqasi uchun oziq yoki boshpana. Bitta bo‘g‘in yo‘qolsa, butun to‘r o‘zgaradi.',
      },
      air: {
        label: 'Havo',
        title: 'Salqin va nam havo',
        text: 'Soyabon quyosh nurini to‘sadi, bug‘lanish havoni salqinlatadi. O‘rmon ichi atrofidagidan salqinroq va namroq bo‘ladi.',
      },
    },
  },

  cut: {
    prompt: 'Endi tutqichni o‘zingiz suring.',
    sliderLabel: 'O‘rmonning yo‘qotilishi',
    left: 'o‘rmon',
    right: 'kesilgan yer',
    disclaimer: 'Ko‘rsatkichlar illyustrativ: nisbiy o‘zgarishni ko‘rsatadi, real o‘lchov emas.',
    indicators: {
      canopy: 'Daraxt qoplami',
      habitat: 'Yashash muhiti',
      soil: 'Tuproq himoyasi',
      water: 'Suv tozaligi',
      humidity: 'Havo namligi',
    },
    moments: [
      'Avval chekkasi kesiladi. Soyabonda bo‘shliqlar paydo bo‘ladi.',
      'Yomg‘ir endi tuproqqa singmaydi — sirt bo‘ylab oqib ketadi.',
      'Daryo loyqalanadi. Hayvonlar ketadi yoki yo‘qoladi.',
      'Daraxtlar ketdi. Ular bilan soya, namlik va boshpana ham ketdi.',
    ],
    statIntro: 'Dunyoda har yili kesilayotgan o‘rmon:',
  },

  causes: {
    title: 'Bosim har tomondan keladi.',
    instruction: 'Sababni tanlang va o‘rmon qanday o‘zgarishini kuzating.',
    reset: 'O‘rmonni qaytarish',
    drivers: {
      agriculture: {
        label: 'Ekin maydonlari',
        text: 'O‘rmon dalaga aylantiriladi. Dunyo miqyosida bu — o‘rmon kesilishining eng katta sababi.',
      },
      grazing: {
        label: 'Yaylov va chorva',
        text: 'O‘rmon yaylovga aylanadi. Chorva yosh nihollarni yeb, o‘rmonning o‘zini tiklashiga yo‘l qo‘ymaydi.',
      },
      logging: {
        label: 'Yog‘och tayyorlash',
        text: 'Tanlab kesish o‘rmonni darhol yo‘q qilmasligi mumkin, lekin uni zaiflashtiradi va ichkariga yo‘l ochadi.',
      },
      roads: {
        label: 'Yo‘llar va aholi punktlari',
        text: 'Yo‘l o‘rmonni bo‘laklarga ajratadi. Uning ikki tomonida yangi kesishlar va qishloqlar paydo bo‘ladi.',
      },
      mining: {
        label: 'Konchilik',
        text: 'Kon maydoni kichik bo‘lishi mumkin, ammo uning tuproq, suv va atrofdagi o‘rmonga ta’siri katta.',
      },
      fire: {
        label: 'Yong‘inlar',
        text: 'Ba’zi o‘rmonlarda yong‘in tabiiy jarayon. Lekin qurg‘oqchilik va kesish yong‘inlarni kuchliroq va tez-tez qiladi.',
      },
    },
    nuance: 'Sabablarning ulushi har mintaqada turlicha. Markaziy Osiyo tog‘larida, masalan, ortiqcha mol boqish va o‘tin uchun kesish asosiy bosim hisoblanadi.',
    ringTitle: 'Dunyo bo‘yicha o‘rmon kesilishi sabablari',
    ringOther: 'boshqa sabablar',
  },

  consequences: {
    title: 'Bitta o‘zgarish — bir necha oqibat.',
    chains: {
      biodiversity: {
        label: 'Biologik xilma-xillik',
        steps: ['O‘rmon kesiladi', 'Soyabon uziladi', 'Yashash joylari bo‘laklanadi', 'Turlar yo‘qoladi yoki ko‘chib ketadi'],
      },
      soilWater: {
        label: 'Tuproq va suv',
        steps: ['Ildizlar yo‘qoladi', 'Tuproq ochilib qoladi', 'Yomg‘ir tuproqni yuvib ketadi', 'Daryolar loyqalanadi, suv rejimi buziladi'],
      },
      climate: {
        label: 'Iqlim',
        steps: ['O‘rmon yo‘qoladi', 'Saqlangan uglerod havoga chiqadi', 'Uglerod yutilishi kamayadi', 'Iqlim o‘zgarishi kuchayadi'],
      },
    },
    closing: 'Bu zanjirlar alohida emas — ular bir-birini kuchaytiradi.',
  },

  world: {
    title: 'O‘rmonlar Yer yuzida notekis taqsimlangan.',
    instruction: 'Hududni tanlang.',
    tropics: 'Tropik kamar',
    reset: 'Butun dunyo',
    overview: 'Dunyo o‘rmonlari',
    overviewText: 'O‘rmonlar quruqlikning qariyb uchdan birini qoplaydi. Ularning qariyb yarmi tropik mintaqada.',
    regions: {
      amazon: {
        name: 'Amazoniya',
        text: 'Dunyodagi eng katta tropik yomg‘ir o‘rmoni. U o‘z yomg‘irining bir qismini o‘zi yaratadi.',
      },
      congo: {
        name: 'Kongo havzasi',
        text: 'Afrikadagi eng katta tropik o‘rmon massivi — minglab turlar uchun uy.',
      },
      seasia: {
        name: 'Janubi-Sharqiy Osiyo',
        text: 'Orollardagi tropik o‘rmonlar qishloq xo‘jaligi plantatsiyalari kengayishidan katta bosim ostida.',
      },
      boreal: {
        name: 'Shimoliy (boreal) o‘rmonlar',
        text: 'Rossiya, Kanada va Skandinaviyaning ignabargli o‘rmonlari. Sovuqda sekin o‘sadi, tuproqda ko‘p uglerod saqlaydi.',
      },
      centralasia: {
        name: 'Markaziy Osiyo tog‘lari',
        text: 'Quruq mintaqadagi archa va yong‘oq-mevali o‘rmonlar kichik, ammo tog‘ yonbag‘irlari va suv manbalari uchun muhim.',
      },
      uk: { name: 'Buyuk Britaniya', text: 'Bir asr ichida o‘rmonzorlarini qayta ko‘paytirgan mamlakat. Hikoyasi — keyingi bobda.' },
      japan: { name: 'Yaponiya', text: 'O‘rmon qoplami yuqori mamlakat. Lekin uning katta qismi inson qo‘lida ekilgan.' },
      aral: { name: 'Orolbo‘yi', text: 'Bizning hikoyamiz shu yerda davom etadi.' },
    },
  },

  cases: {
    kicker: 'Uch hikoya',
    uk: {
      title: 'Buyuk Britaniya',
      lead: 'Bir asr oldin o‘rmonzorlar juda kam qolgan edi. Bugun ular deyarli uch baravar ko‘p.',
      scrub: 'Yilni tanlang',
      nuance: 'O‘sish asosan yangi ekilgan o‘rmonzorlar hisobiga bo‘lgan. Ular qadimiy o‘rmonlar o‘rnini to‘liq bosa olmaydi.',
    },
    japan: {
      title: 'Yaponiya',
      lead: 'Mamlakatning katta qismi o‘rmon. Ammo bu o‘rmonlarning salmoqli qismi ekilgan.',
      toggleAll: 'Umumiy qoplam',
      toggleType: 'Tabiiy va ekilgan',
      natural: 'tabiiy va yarim tabiiy',
      forest: 'o‘rmon',
      world: 'Dunyo o‘rtachasi',
      planted: 'ekilgan',
      nuance: 'O‘rmon maydoni o‘nlab yillar davomida deyarli o‘zgarmagan. Ekilgan o‘rmonlarni parvarish qilish va ulardan oqilona foydalanish — alohida muammo.',
    },
    uzbekistan: {
      title: 'O‘zbekiston',
      lead: 'Bizning yurt — kam o‘rmonli, quruq iqlimli mamlakat. Shuning uchun har bir daraxt qadrli.',
      bridge: 'Endi shimoli-g‘arbga — Orol tomon boramiz.',
      mountains: 'Tog‘lardagi archazor va yong‘oqzorlar',
      desert: 'Cho‘ldagi saksovulzorlar',
      aral: 'Orolning qurigan tubi',
    },
  },

  aral: {
    place: 'Orolbo‘yi',
    places: { syr: 'Sirdaryo', amu: 'Amudaryo', moynaq: 'Mo‘ynoq', kz: 'Qozog‘iston', uz: 'O‘zbekiston' },
    once: 'Bir paytlar bu yerda dengiz bor edi.',
    mapNote: 'Sxematik tasvir — aniq xarita emas.',
    mapThen: 'oltmishinchi yillar',
    mapNow: 'bugun',
    cause: 'Daryolar suvi sug‘orishga olindi. Dengiz chekindi.',
    left: 'Ortida qum, tuz va chang qoldi.',
    wind: 'Shamol tuzli changni uzoqlarga olib ketadi.',
    planting: 'Endi qurigan tubga cho‘l o‘simliklari ekilmoqda.',
    saxaul: 'Qora saksovul',
    saxaulLatin: 'Haloxylon aphyllum',
    roots: 'Ildizlar qumni ushlaydi. Chang kamroq ko‘tariladi.',
    notSea: 'Bu dengizni qaytarmaydi.',
    partial: 'Lekin yerni himoya qiladi — qisman, sekin, mehnat bilan.',
    reported: 'rasmiy ma’lumotlarga ko‘ra',
    limits: 'Sho‘r tuproqda ko‘chatlarning ko‘pi tutib qolmaydi. Ekilgan maydonlarni parvarish qilish va mustaqil kuzatish kerak.',
  },

  simulator: {
    title: 'Yer sizning qo‘lingizda',
    intro: 'Hududni boshqaring. Har bir qaror nimanidir beradi va nimanidir oladi.',
    disclaimer: 'Bu ilmiy model emas. Bu ekologik bog‘liqliklarni soddalashtirib ko‘rsatadigan interaktiv model.',
    toolsLabel: 'Harakat',
    gridLabel: 'Hudud xaritasi. Katakni tanlash uchun strelkalar, harakatni qo‘llash uchun Enter.',
    advance: 'yil o‘tkazish',
    reset: 'Qaytadan',
    rulesTitle: 'Model qoidalari',
    year: 'yil',
    tools: {
      protect: { label: 'Himoya qilish', hint: 'O‘rmonni qo‘riqlanadigan hududga aylantiradi.' },
      clear: { label: 'Kesish', hint: 'O‘rmonni yog‘och uchun kesadi — yer ochiladi.' },
      farm: { label: 'Ekin maydoni', hint: 'Ochiq yerni dalaga aylantiradi — oziq-ovqat beradi.' },
      restore: { label: 'Qayta tiklash', hint: 'Ochiq yoki eskirgan yerga mahalliy daraxtlar ekadi. Ular yillar o‘tib o‘sadi.' },
      improve: { label: 'Barqaror foydalanish', hint: 'Dalani agroo‘rmonga aylantiradi: daraxtlar va ekinlar birga.' },
    },
    indicators: {
      forest: 'O‘rmon',
      biodiversity: 'Biologik xilma-xillik',
      soil: 'Tuproq',
      water: 'Suv',
      carbon: 'Uglerod',
      food: 'Oziq-ovqat',
    },
    messages: {
      start: 'Harakatni tanlang, so‘ng xaritadagi katakni bosing.',
      cleared: 'Kesildi: yog‘och olindi, lekin yer ochilib qoldi.',
      clearedWater: 'Daryo bo‘yidagi o‘rmon kesildi — suv loyqalanadi.',
      protected: 'Qo‘riqlanadigan hudud: bu o‘rmon endi kesilmaydi.',
      farmed: 'Yangi dala: oziq-ovqat ko‘paydi, tuproq esa bosim ostida.',
      restored: 'Mahalliy ko‘chatlar ekildi. O‘rmon bo‘lishi uchun yillar kerak.',
      improved: 'Agroo‘rmon: hosil biroz kamroq, lekin tuproq va suv yaxshiroq.',
      invalidProtected: 'Bu o‘rmon qo‘riqlanadi — uni kesib bo‘lmaydi.',
      invalidType: 'Bu harakatni bu katakka qo‘llab bo‘lmaydi.',
      years: '{n} yil o‘tdi.',
      grown: 'Yosh o‘rmon voyaga yetdi.',
      demand: 'Aholi o‘sdi — ko‘proq oziq-ovqat kerak.',
      pressure: 'Oziq-ovqat yetishmadi: qo‘riqlanmagan o‘rmon chekkasi dalaga aylantirildi.',
      deficit: 'Oziq-ovqat yetishmayapti — aholi ehtiyoji qondirilmayapti.',
    },
    rules: [
      'Tutash o‘rmon bo‘lak-bo‘lak o‘rmondan ko‘ra ko‘proq hayotni saqlaydi.',
      'Ochiq yer tuproqni eng ko‘p yo‘qotadi; dala va yaylov — o‘rtacha; agroo‘rmon — kam.',
      'Daryo bo‘yidagi daraxtlar suvni toza saqlaydi; ochiq yer va dalalar uni loyqalaydi.',
      'Ekilgan ko‘chat {mature} yilda o‘rmonga aylanadi (soddalashtirilgan). Shu vaqtgacha u kam uglerod saqlaydi.',
      'Har {years} yilda aholi o‘sadi va ko‘proq oziq-ovqat kerak bo‘ladi.',
      'Oziq-ovqat yetishmasa, qo‘riqlanmagan o‘rmon chekkasi dalaga aylantiriladi.',
      'Qo‘riqlanadigan o‘rmonni kesib bo‘lmaydi; ekin maydoni eng ko‘p, agroo‘rmon kamroq, yaylov esa eng kam oziq beradi.',
    ],
    yearLabel: 'Yil',
    logLabel: 'Oqibatlar',
    levels: { low: 'past', mid: 'o‘rtacha', high: 'yuqori' },
    tiles: {
      forest: 'o‘rmon',
      protected: 'qo‘riqlanadigan o‘rmon',
      young: 'yosh o‘rmon',
      farm: 'ekin maydoni',
      agroforest: 'agroo‘rmon',
      pasture: 'yaylov',
      bare: 'ochiq yer',
      water: 'daryo',
      village: 'qishloq',
    },
  },

  recovery: {
    plant: 'Ko‘chat ekish — bir necha daqiqa.',
    sapling: 'Yosh daraxt bo‘lishi uchun — yillar.',
    structure: 'O‘rmon tuzilmasi shakllanishi uchun — o‘nlab yillar.',
    century: 'Ba’zi xususiyatlar tiklanishi uchun — yuz yildan ortiq.',
    notEqual: 'Ekish muhim. Ammo yetuk o‘rmonni saqlash bilan teng emas.',
    studyNote: 'Tropik o‘rmonlarning tabiiy qayta o‘sishi bo‘yicha tadqiqot: yetuk o‘rmon ko‘rsatkichlarining to‘qson foiziga yetish vaqti.',
  },

  futures: {
    a: 'A yo‘l',
    aLabel: 'Yemirilish davom etadi',
    b: 'B yo‘l',
    bLabel: 'Himoya va tiklash',
    seam: 'Ikki kelajakni solishtirish',
    disclaimer: 'Bu prognoz emas. Bu oldingi boblarda ko‘rgan bog‘liqliklarning vizual xulosasi.',
    now: 'bugun',
    later: 'kelajak',
    end1: 'O‘rmon kelajagi o‘z-o‘zidan hal bo‘lmaydi.',
    end2: 'Uni qanday qoldirishimiz bugungi qarorlarimizga bog‘liq.',
  },

  finale: {
    actionsTitle: 'Bugun nima qilish mumkin?',
    actions: [
      'Mavjud yetuk o‘rmonlarni saqlash — ularni hech qanday ko‘chat almashtira olmaydi.',
      'Mahalliy turlar bilan ekish va ko‘chatni yillar davomida parvarish qilish.',
      'Yerdan oqilona foydalanish: daryo bo‘yida daraxt qatorlari, agroo‘rmonchilik, yaylovlarni navbat bilan boqish.',
      'Qurg‘oqchil yerlarda tuproqni o‘simliklar bilan mustahkamlash.',
      'Qarorlar va natijalarni ochiq kuzatish: necha ko‘chat ekildi emas, nechtasi o‘sdi.',
    ],
    echoBefore: 'Bir paytlar bu yerda o‘rmon bor edi.',
    echoAfter: 'Bu yerda o‘rmon bo‘lib qolsin.',
    thanks: 'Rahmat.',
    sources: 'Manbalar',
    restart: 'Boshiga qaytish',
    credits: 'Barcha tasvirlar va tovushlar ushbu taqdimot uchun dasturiy yaratilgan. Xarita: Natural Earth (world-atlas).',
  },
} as const;
