import type { Source } from './types';

/**
 * Central source registry. Every Stat in facts.ts references one of these ids.
 * Accessed dates reflect the fact-check pass (2026-10-01). URLs were confirmed
 * from the publishers' own pages via search; see RESEARCH_GAPS for caveats.
 */
const ACCESSED = '2026-10-01';

const SOURCE_LIST = [
  {
    id: 'fao-fra-2025',
    organization: 'FAO',
    title: 'Global Forest Resources Assessment 2025 — Key findings',
    year: 2025,
    url: 'https://openknowledge.fao.org/server/api/core/bitstreams/2dee6e93-1988-4659-aa89-30dd20b43b15/content/FRA-2025/key-findings.html',
    accessed: ACCESSED,
    usedFor: 'Dunyo o‘rmon maydoni, o‘rmon kesilishi va sof yo‘qotish sur’atlari, tropiklar ulushi, uglerod zaxirasi.',
  },
  {
    id: 'fao-fra-2020-rss',
    organization: 'FAO',
    title: 'COP26: Agricultural expansion drives almost 90 percent of global deforestation (FRA 2020 Remote Sensing Survey)',
    year: 2021,
    url: 'https://www.fao.org/newsroom/detail/cop26-agricultural-expansion-drives-almost-90-percent-of-global-deforestation/en',
    accessed: ACCESSED,
    usedFor: 'O‘rmon kesilishi sabablari, 2000–2018 yillar, butun dunyo.',
  },
  {
    id: 'wri-gfw-2024',
    organization: 'World Resources Institute / Global Forest Watch',
    title: 'Global Forest Loss Shatters Records in 2024, Fueled by Massive Fires',
    year: 2025,
    url: 'https://www.wri.org/news/release-global-forest-loss-shatters-records-2024-fueled-massive-fires',
    accessed: ACCESSED,
    usedFor: 'Tropik birlamchi o‘rmonlar yo‘qotilishi va yong‘inlar ulushi (2024). “Daraxt qoplami yo‘qotilishi” FAO “o‘rmon kesilishi” ta’rifidan farq qiladi.',
  },
  {
    id: 'fao-sofo-2020',
    organization: 'FAO & UNEP',
    title: 'The State of the World’s Forests 2020: Forests, biodiversity and people',
    year: 2020,
    url: 'https://openknowledge.fao.org/server/api/core/bitstreams/8f8f2820-6df4-4746-9295-e9356148f8a2/content/CA8642EN.html',
    accessed: ACCESSED,
    usedFor: 'O‘rmonlar va biologik xilma-xillik.',
  },
  {
    id: 'gcb-2025',
    organization: 'Global Carbon Project (Friedlingstein et al.)',
    title: 'Global Carbon Budget 2025, Earth System Science Data 18: 3211',
    year: 2026,
    url: 'https://essd.copernicus.org/articles/18/3211/2026/',
    accessed: ACCESSED,
    usedFor: 'Yerdan foydalanish o‘zgarishidan CO₂ chiqindilari.',
  },
  {
    id: 'staal-2018',
    organization: 'Staal et al., Nature Climate Change',
    title: 'Forest-rainfall cascades buffer against drought across the Amazon (doi:10.1038/s41558-018-0177-y)',
    year: 2018,
    url: 'https://doi.org/10.1038/s41558-018-0177-y',
    accessed: ACCESSED,
    usedFor: 'O‘rmonlar va yomg‘ir aylanishi.',
  },
  {
    id: 'fao-forest-water',
    organization: 'FAO',
    title: 'Sustainable Forest Management Toolbox — SFM for soil and water conservation',
    url: 'https://www.fao.org/forestry/sfm/sfm-for-soil-and-water-conservation/',
    accessed: ACCESSED,
    usedFor: 'O‘rmonlar, tuproq eroziyasi va chuchuk suv.',
  },
  {
    id: 'uk-woodland-2026',
    organization: 'Forest Research (UK)',
    title: 'Provisional Woodland Statistics 2026',
    year: 2026,
    url: 'https://www.gov.uk/government/statistics/provisional-woodland-statistics-2026',
    accessed: ACCESSED,
    usedFor: 'Buyuk Britaniyadagi o‘rmonzorlar maydoni, 2026-yil 31-mart holatiga.',
  },
  {
    id: 'uk-forestry-stats-history',
    organization: 'Forest Research (UK)',
    title: 'Forestry Statistics 2022, Chapter 1: Woodland area and planting (historical woodland cover)',
    year: 2022,
    url: 'https://cdn.forestresearch.gov.uk/2022/09/Ch1_Woodland_2022.pdf',
    accessed: ACCESSED,
    usedFor: 'Buyuk Britaniya o‘rmonzorlari ulushining tarixiy qatori (1905–2022). Turli yillardagi inventarizatsiyalarda ta’riflar biroz farq qilgan.',
  },
  {
    id: 'uk-lords-1919',
    organization: 'House of Lords Library',
    title: 'Forestry Act 1919: 100 Years (LLN-2019-0066)',
    year: 2019,
    url: 'https://lordslibrary.parliament.uk/research-briefings/lln-2019-0066/',
    accessed: ACCESSED,
    usedFor: '1919-yilgi O‘rmon to‘g‘risidagi qonun va O‘rmon xo‘jaligi komissiyasining tashkil etilishi.',
  },
  {
    id: 'japan-forestry-agency',
    organization: 'Forestry Agency, MAFF (Japan)',
    title: 'Annual Report on Forest and Forestry in Japan, FY2024 (summary)',
    year: 2025,
    url: 'https://www.maff.go.jp/e/data/publish/AnnualReportonForestandForestry/AnnualReportonForestandForestryinJapan_FY2024.pdf',
    accessed: ACCESSED,
    usedFor: 'Yaponiya o‘rmonlari maydoni, ulushi va ekilgan o‘rmonlar.',
  },
  {
    id: 'wb-forest-indicator',
    organization: 'World Bank (FAO ma’lumotlari asosida)',
    title: 'Forest area (% of land area), indicator AG.LND.FRST.ZS',
    year: 2023,
    url: 'https://data.worldbank.org/indicator/AG.LND.FRST.ZS?locations=JP-UZ',
    accessed: ACCESSED,
    usedFor: 'Mamlakatlar bo‘yicha o‘rmon ulushi (Yaponiya, O‘zbekiston).',
  },
  {
    id: 'wb-uzbekistan-forest-note',
    organization: 'World Bank',
    title: 'Uzbekistan Country Forest Note',
    year: 2022,
    url: 'https://documents1.worldbank.org/curated/en/099250007072236900/pdf/P1708700ef21870290b1a9019310003c250.pdf',
    accessed: ACCESSED,
    usedFor: 'O‘zbekiston o‘rmon maydoni (FAO FRA 2020 asosida), tog‘ o‘rmonlari va ularga bosim.',
  },
  {
    id: 'undp-yashil-makon',
    organization: 'UNDP Uzbekistan & UNECE',
    title: 'UNDP and UNECE step forward to support Yashil Makon / Green Nation initiative',
    year: 2022,
    url: 'https://www.undp.org/uzbekistan/press-releases/undp-and-unece-step-forward-support-yashil-makon/green-nation-initiative',
    accessed: ACCESSED,
    usedFor: '“Yashil makon” umummilliy loyihasi.',
  },
  {
    id: 'uz-president-aral-2026',
    organization: 'O‘zbekiston Respublikasi Prezidenti matbuot xizmati',
    title: 'National Dendrological Park project launched (president.uz, April 2026)',
    year: 2026,
    url: 'https://president.uz/en/lists/view/9067',
    accessed: ACCESSED,
    usedFor: 'Orol dengizining qurigan tubida barpo etilgan himoya o‘rmonzorlari — rasmiy bayonot.',
  },
  {
    id: 'shields-2026',
    organization: 'Shields, Environment and Planning E',
    title: 'Independent remote-sensing assessment of Aral seabed afforestation (doi:10.1177/25148486261447677)',
    year: 2026,
    url: 'https://doi.org/10.1177/25148486261447677',
    accessed: ACCESSED,
    usedFor: 'Rasmiy e’lon qilingan gektarlar va sun’iy yo‘ldoshda ko‘rinadigan o‘simlik qoplami o‘rtasidagi farq.',
  },
  {
    id: 'esa-aral-2025',
    organization: 'European Space Agency',
    title: 'Earth from Space: The shrinking Aral Sea',
    year: 2025,
    url: 'https://www.esa.int/ESA_Multimedia/Images/2025/04/Earth_from_Space_The_shrinking_Aral_Sea',
    accessed: ACCESSED,
    usedFor: 'Orol dengizining 1960-yildagi maydoni.',
  },
  {
    id: 'nasa-aral',
    organization: 'NASA Earth Observatory',
    title: 'World of Change: Shrinking Aral Sea',
    url: 'https://science.nasa.gov/earth/earth-observatory/world-of-change/aral-sea/',
    accessed: ACCESSED,
    usedFor: 'Orol qurishining sabablari va bosqichlari; sxematik qirg‘oq chiziqlari uchun tayanch.',
  },
  {
    id: 'unep-aral',
    organization: 'UNEP',
    title: 'Greening a toxic dryland',
    url: 'https://www.unep.org/news-and-stories/story/greening-toxic-dryland',
    accessed: ACCESSED,
    usedFor: 'Orol dengizi tarixiy hajmining taxminan 10 foizi qolgani; qurigan tubdan ko‘tariladigan tuzli chang.',
  },
  {
    id: 'wb-kokaral',
    organization: 'World Bank',
    title: 'Syr Darya Control and Northern Aral Sea Project — Implementation Completion Report (ICR0000874)',
    url: 'https://documents1.worldbank.org/curated/en/189171468038051254/pdf/ICR8740P0460450Official0Use0Only090.pdf',
    accessed: ACCESSED,
    usedFor: 'Ko‘karal to‘g‘oni (2005) va Shimoliy Orolning qisman tiklanishi.',
  },
  {
    id: 'novitskiy-2012',
    organization: 'Novitskiy et al., in Breckle et al. (eds.), Springer',
    title: 'Phytomelioration in the Southern Aralkum — Aralkum: a Man-Made Desert (Ecological Studies 218)',
    year: 2012,
    url: 'https://link.springer.com/chapter/10.1007/978-3-642-21117-1_16',
    accessed: ACCESSED,
    usedFor: 'Qora saksovul (Haloxylon aphyllum) va Orol tubidagi fitomelioratsiya; sho‘rxok tuproqlarda past tutish darajasi.',
  },
  {
    id: 'cajwr-2021-saxaul',
    organization: 'Central Asian Journal of Water Research',
    title: 'State of Saxaul Plantations in Kazakhstan’s Section of the Aral Sea Region',
    year: 2021,
    url: 'https://water-ca.org/article/state-of-saxaul-plantations',
    accessed: ACCESSED,
    usedFor: 'Saksovul ko‘chatlarining tuproqqa qarab juda turlicha tutishi.',
  },
  {
    id: 'poorter-2021',
    organization: 'Poorter et al., Science 374: 1370',
    title: 'Multidimensional tropical forest recovery (doi:10.1126/science.abh3629)',
    year: 2021,
    url: 'https://doi.org/10.1126/science.abh3629',
    accessed: ACCESSED,
    usedFor: 'Tabiiy qayta o‘sayotgan tropik o‘rmonlarning tiklanish vaqtlari (77 hudud).',
  },
  {
    id: 'fao-mountain-juniper',
    organization: 'FAO Mountain Partnership',
    title: 'Juniper forests and the survival of high mountain communities in Central Asia',
    url: 'https://www.fao.org/mountain-partnership/news/newsroom/news-detail/Juniper-forests-and-the-survival-of-high-mountain-communities-in-Central-Asia/en',
    accessed: ACCESSED,
    usedFor: 'Markaziy Osiyodagi archa o‘rmonlari va ularga bosim (ortiqcha mol boqish, noqonuniy kesish).',
  },
  {
    id: 'wilson-2019-oryx',
    organization: 'Wilson et al., Oryx 53(3)',
    title: 'The future of walnut–fruit forests in Kyrgyzstan and the status of the iconic Endangered apple Malus niedzwetzkyana',
    year: 2019,
    url: 'https://www.cambridge.org/core/journals/oryx/article/future-of-walnutfruit-forests-in-kyrgyzstan-and-the-status-of-the-iconic-endangered-apple-malus-niedzwetzkyana/FEC98C686662EA95FFE67C4548B680B7',
    accessed: ACCESSED,
    usedFor: 'G‘arbiy Tyan-Shan yong‘oq-mevali o‘rmonlari va chorva/o‘tin bosimi.',
  },
] as const satisfies readonly Source[];

export type SourceId = (typeof SOURCE_LIST)[number]['id'];

export const SOURCES: readonly (Source & { id: SourceId })[] = SOURCE_LIST;

export const sourceById = (id: string): Source | undefined => SOURCES.find((s) => s.id === id);
